name: Insights

on:
  - pull_request

jobs:
  insights:
    runs-on: ubuntu-latest

    name: PHP Insights checks
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        working-directory: ./src
        run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist

      - name: Insights Analyse
        working-directory: ./src
        run: php artisan insights -n --ansi --format=github-action
